### ISSUE TITLE
_pagination parameter not returning Pagination hash / result set size

### ISSUE THREAD

**Issue by ygagnon** [sparkapi/sparkapi4p2#51]
I'm noticing that when using the GetListings() method, and when attempting to assign a "_pagination" value of "1", .. that I am not getting the expected Pagination section in the result:

**"Pagination": {
  "TotalRows": 78,
  "PageSize": 25,
  "TotalPages": 4,
  "CurrentPage": 1
}**

Here is my code snippet:

**$resultAll = $api->GetListings(
array(
	'_pagination' => 1,	
	'_filter' => "PropertyType eq 'A' and (MlsStatus eq 'Active' or MlsStatus eq 'Pending'')",
	'_limit' => 25,	
	'_expand' => 'PrimaryPhoto'
	)
);
print_r($resultAll);**

Obviously this presents a problem, as I have no way of knowing how to set up my pagination, as I have no "TotalRows" value available to me that I can apply some simple math to.  Note that I also tried specifying a _pagination value of "count" .. (both with surrounding quotes and without) but that just returns an empty array.  

Lastly, note that when I specify these same queries using Postman, .. I do get the expected Pagination section in the result.  It just doesn't appear to be working with the PHP client library.  

Is there some vital piece that I'm missing, perhaps?  If so, how do I return the TotalRows value?  Or is not technially possible to retrieve this information using the PHP client library?    

Thanks,
-- Yvan

**Comment by dgmyrek** [comment]
Hi Yvan, when _pagination is set to '1' or 'count' the public pagination variables here (https://github.com/sparkapi/sparkapi4p2/blob/master/lib/Core.php#L61) will be populated in the client.  

Adding `echo $api->last_count` after your API call should display the "TotalRows".

**Comment by ygagnon** [comment]
Ahh ,.. I see.  Thanks so much!  I now see that this information is also part of the wiki, so I've gone ahead and bookmarked that page for future reference. 

https://github.com/sparkapi/sparkapi4p2/wiki/Pagination-Information

By any chance, are any of the other methods that are contained within Core.php documented anywhere? I ask because I don't see any examples for them in examples.php.  I'm assuming that their implementations are meant to be self-explanatory, though I was curious to see if there might be any more documentation regarding them. 

Thanks again,
-- Yvan

**Comment by dgmyrek** [comment]
We don't have any documentation specific to the client functions since they are intended to be self documenting. Detailed API docs that fully outline the services that each of those wrapper functions point at can be found here though: http://sparkplatform.com/docs/api_services/read_first. 

For example a wrapper function like https://github.com/sparkapi/sparkapi4p2/blob/master/lib/Core.php#L518 
is referencing this documentation: http://sparkplatform.com/docs/api_services/listing_carts
