### ISSUE TITLE
Error in example.php

### ISSUE THREAD

**Issue by mlacunza** [sparkapi/sparkapi4p2#52]
This file: https://github.com/sparkapi/sparkapi4p2/blob/master/examples.php have an error:

Line 18:
$api = new SparkAPI_SparkAPI_Bearer("your_access_token_here"); 

Correct version:
$api = new SparkAPI_Bearer("your_access_token_here");

**Comment by dgmyrek** [comment]
Good catch. Should be good to go in master now.
